### ISSUE TITLE
Устнаовка чистого clonos не готов чтобы сразу запустить виртуалку с win

### ISSUE THREAD

**Issue by esuslik** [clonos/cp#11]
После установки потребовалось вручную добавить в rc.conf kld_list="if_bridge if_tap nmdm"
Отдельно установать пакет tmux
Еще вроде какой-то пакет но не помню уже какой

**Comment by esuslik** [comment]
имеется ввиду установка из образа clonos iso на железку.

**Comment by olevole** [comment]
fixed, thx!
