### ISSUE TITLE
Upload ISO image not work

### ISSUE THREAD

**Issue by esuslik** [clonos/cp#9]
Clean install of clonos.
When i try to upload an iso image progress bar starts to show that upload is going, but after 1 or 2 minute it stay red and uploading stops.

Can i write issues on russian? my english is not very good

**Comment by olevole** [comment]
Привет! Можно и  на русском) Я планирую в ближайшие 2 недели обновить образ/код, там были некоторые улучшения по части upload. + Перепроверю, отпишусь попозже. Спасибо!

**Comment by esuslik** [comment]
Обновление планируется в ближайшее время?

**Comment by olevole** [comment]
У меня к сож-ю, пока нет времени

**Comment by olevole** [comment]
Кто-то на мыло мне написал, что ему пришлось в nginx.conf в http { } увеличить body:

client_max_body_size    2048m;

но также, проблема может быть в upload_max_filesize, post_max_size в php.ini а также наличии свободного места в /tmp. Мне пока негде проверить, нет оборудования с FBSD

**Comment by hliebel** [comment]
Hi.
Changing:
client_max_body_size 2048m;
Fixed it for me. 
Thanks.

**Comment by olevole** [comment]
Fixes, thanks!
